const course = {
  4: {
    summary: 'Two volumes, eight chapters, and a path built for Grade 4.',
    chapters: [
      ['Place Value & Addition', ['Place value', 'Rounding', 'Add & subtract'], 'Use a place-value chart to see what every digit is worth. When rounding, look at the digit immediately to the right of the place you are rounding to.', 'grid'],
      ['Whole-Number Multiplication', ['Arrays', 'Area models', 'Multi-digit products'], 'An array makes equal groups visible. Split a number into tens and ones, multiply each part, then put the pieces back together.', 'dots'],
      ['Whole-Number Division', ['Equal groups', 'Long division', 'Remainders'], 'Division shares an amount into equal groups. A remainder is what is left after sharing as equally as possible.', 'lines'],
      ['Equations & Word Problems', ['Multi-step plans', 'Variables', 'Factors'], 'A variable is a letter standing in for an unknown number. Use an inverse operation to uncover the missing value.', 'grid'],
      ['Measurement', ['Unit conversions', 'Time and volume', 'Area & perimeter'], 'A conversion changes the unit name but not the amount. Area fills a shape; perimeter travels around its edge.', 'lines'],
      ['Fraction Concepts', ['Equivalent fractions', 'Adding fractions', 'Subtracting fractions'], 'Equivalent fractions name the same amount. When denominators match, the fraction pieces are the same size.', 'fraction'],
      ['Fractions & Decimals', ['Fraction groups', 'Tenths & hundredths', 'Compare decimals'], 'Decimals are another way to show parts of one whole. The first place right of the decimal is tenths; the second is hundredths.', 'fraction'],
      ['Geometry', ['Lines', 'Angles', 'Symmetry'], 'Geometry describes shapes and space. Angles measure turns; a symmetry line creates matching mirror-image halves.', 'lines']
    ]
  },
  5: {
    summary: 'Two volumes, eight chapters, and a path built for Grade 5.',
    chapters: [
      ['Multiplication & Division Problems', ['Equal groups', 'Expressions', 'Factors'], 'Use multiplication for equal groups and comparisons. Parentheses tell you which part to solve first.', 'dots'],
      ['Perimeter & Area', ['Perimeter', 'Area', 'Area models'], 'Perimeter is distance around a shape. Area is the number of square units covering the inside.', 'lines'],
      ['Addition & Subtraction', ['Whole numbers', 'Decimals', 'Place value'], 'Line up digits by their place values. With decimals, the decimal points must line up.', 'grid'],
      ['Angles & Polygons', ['Angles', 'Straight lines', 'Polygons'], 'An angle measures a turn. Polygons are closed shapes made from straight line segments.', 'lines'],
      ['Fraction Addition & Subtraction', ['Equivalent fractions', 'Addition', 'Subtraction'], 'Before adding unlike fractions, rewrite them with equal-size pieces using a common denominator.', 'fraction'],
      ['Volume & Measurement', ['Volume', 'Conversions', 'Layers'], 'Volume is the number of cubic units inside a solid. A rectangular prism has equal layers of cubes.', 'grid'],
      ['Integers & Coordinates', ['Integers', 'Absolute value', 'Coordinate plane'], 'Integers include positive numbers, negative numbers, and zero. Ordered pairs move across, then up or down.', 'lines'],
      ['Advanced Operations', ['Fraction multiplication', 'Long division', 'Decimal operations'], 'Multiply fractions by whole numbers as repeated groups. Check division with multiplication and the remainder.', 'fraction']
    ]
  }
};

const legacyQuestionSets = {
  4: [
    [['Round 386,749 to the nearest thousand.', '387,000', '386,000', '390,000', '380,000'], ['Find 48,376 + 25,849.', '74,225', '73,225', '74,215', '75,225'], ['Find 82,503 - 37,628.', '44,875', '45,875', '44,985', '45,985']],
    [['Use an area model: 23 × 4 = ?', '92', '72', '84', '96'], ['Find 1,426 × 3.', '4,278', '4,238', '4,168', '3,278'], ['Find 24 × 13.', '312', '272', '302', '322']],
    [['What is 864 ÷ 4?', '216', '206', '226', '196'], ['What is the remainder in 29 ÷ 6?', '5', '4', '6', '3'], ['How many vans of 6 seats are needed for 29 students?', '5', '4', '6', '29']],
    [['Solve n + 36 = 91.', '55', '127', '65', '45'], ['A shop has 6 boxes of 24 pencils and gives away 17. How many remain?', '127', '137', '117', '121'], ['Which number is prime?', '29', '21', '27', '33']],
    [['Convert 4 feet to inches.', '48', '16', '40', '400'], ['A 7 m by 4 m garden has what area?', '28 square m', '22 m', '11 square m', '56 square m'], ['Convert 3 kilograms to grams.', '3,000', '300', '30', '30,000']],
    [['Which fraction is equivalent to 1/2?', '2/4', '1/4', '3/4', '2/3'], ['What is 3/8 + 2/8?', '5/8', '5/16', '1/8', '6/8'], ['What is 7/10 - 3/10?', '4/10', '4/20', '10/10', '3/7']],
    [['What is 3 × 2/5?', '6/5', '6/10', '5/6', '2/15'], ['Write 7/10 as a decimal.', '0.7', '0.07', '7.0', '0.70'], ['Which is greater?', '0.75', '0.7', 'They are equal', 'Cannot tell']],
    [['Which has exactly one endpoint?', 'Ray', 'Line', 'Line segment', 'Parallel lines'], ['Classify a 120° angle.', 'Obtuse', 'Acute', 'Right', 'Straight'], ['How many lines of symmetry does a square have?', '4', '1', '2', '0']]
  ],
  5: [
    [['Four boxes have 7 books each. How many books?', '28', '11', '24', '35'], ['Evaluate (8 + 2) × 5.', '50', '18', '20', '40'], ['Which is a factor of 24?', '6', '5', '7', '11']],
    [['A 6 by 4 rectangle has what perimeter?', '20', '24', '10', '48'], ['A 6 by 4 rectangle has what area?', '24 square units', '20 units', '10 square units', '48 square units'], ['Area is 35 square units and width is 5. Length?', '7', '30', '40', '175']],
    [['Find 47,891 + 23,109.', '71,000', '70,000', '71,100', '70,100'], ['Find 90,000 - 31,000.', '59,000', '61,000', '69,000', '49,000'], ['Find 3.40 + 0.65.', '4.05', '3.105', '3.95', '4.50']],
    [['What type is a 45° angle?', 'Acute', 'Right', 'Obtuse', 'Straight'], ['A straight line totals how many degrees?', '180', '90', '360', '100'], ['How many sides does a hexagon have?', '6', '5', '7', '8']],
    [['Which is equivalent to 1/3?', '2/6', '2/3', '3/6', '1/6'], ['Find 1/3 + 1/6.', '1/2', '2/9', '2/6', '1/9'], ['Find 3/4 - 1/4.', '1/2', '2/4', '3/8', '1/4']],
    [['What is the volume of 4 × 3 × 2 prism?', '24 cubic units', '9 square units', '12 units', '24 square units'], ['Convert 3 feet to inches.', '36', '9', '30', '300'], ['12 cubes per layer × 3 layers = ?', '36 cubic units', '15 cubic units', '9 cubic units', '24 cubic units']],
    [['What is |-5|?', '5', '-5', '0', '10'], ['Which quadrant contains (3, -2)?', 'IV', 'I', 'II', 'III'], ['What is the x-coordinate in (3, -2)?', '3', '-2', '1', '5']],
    [['Find 3/4 × 4.', '3', '3/16', '7/4', '1'], ['Find 864 ÷ 7.', '123 R 3', '124 R 2', '123 R 1', '122 R 4'], ['Find 2.4 ÷ 0.3.', '8', '0.8', '80', '0.08']]
  ]
};

function strategyQuestion(concept, chapterName, number) {
  const prompts = [
    [`Which idea is most useful for a ${concept.toLowerCase()} challenge in ${chapterName}?`, 'Use the model and match each number to its place or part.', 'Guess before reading the question.', 'Change every number to zero.', 'Use a different operation without checking.'],
    [`Before solving a ${concept.toLowerCase()} problem, what should you do first?`, 'Read what the problem is asking and identify the important numbers.', 'Choose the longest answer.', 'Skip the model.', 'Start with the final answer.'],
    [`Which habit helps you check work on ${concept.toLowerCase()}?`, 'Use an estimate or a related operation to see whether the answer makes sense.', 'Always pick the largest number.', 'Erase the equation.', 'Ignore units and labels.'],
    [`A classmate is stuck on ${concept.toLowerCase()}. What is the best next step?`, 'Draw or use the chapter model to organize the math idea.', 'Give up after one try.', 'Pick an answer at random.', 'Write a new unrelated question.'],
    [`Which statement about ${concept.toLowerCase()} is true?`, 'A clear model can show how the numbers and operations are connected.', 'The answer never needs checking.', 'All problems use the same operation.', 'Units are never important.'],
    [`What should a strong math explanation include for ${concept.toLowerCase()}?`, 'The operation or model used and why it gives the answer.', 'Only the answer with no work.', 'A different topic.', 'A list of random numbers.'],
    [`After you solve a ${concept.toLowerCase()} problem, what is a smart final check?`, 'Ask whether the result is reasonable for the situation.', 'Make the answer much larger.', 'Delete the units.', 'Never look at the question again.']
  ];
  const item = prompts[number];
  item.concept = number % 3;
  return item;
}

const seedConceptMaps = {
  4: [[1, 2, 2], [0, 1, 2], [0, 1, 2], [1, 0, 2], [0, 2, 1], [0, 1, 2], [0, 1, 2], [0, 1, 2]],
  5: [[0, 1, 2], [0, 1, 1], [0, 0, 1], [0, 1, 2], [0, 1, 2], [0, 1, 2], [1, 1, 1], [0, 1, 2]]
};

function expandQuestionSets(seeds) {
  const expanded = {};
  for (const [grade, chapters] of Object.entries(seeds)) {
    expanded[grade] = chapters.map((questions, chapterIndex) => {
      const chapter = course[grade].chapters[chapterIndex];
      const calculationQuestions = questions.map((question, index) => {
        const copy = [...question];
        copy.concept = seedConceptMaps[grade][chapterIndex][index];
        return copy;
      });
      const strategyQuestions = Array.from({ length: 7 }, (_, index) => strategyQuestion(chapter[1][index % 3], chapter[0], index));
      return [...calculationQuestions, ...strategyQuestions];
    });
  }
  return expanded;
}

const questionSets = expandQuestionSets(legacyQuestionSets);
const placeValueQuestions = [
  ['In 582,641, what is the value of the 8?', '80,000', '8,000', '800,000', '800'],
  ['Which number has 7 in the ten-thousands place?', '472,315', '427,315', '427,135', '42,731'],
  ['Write “six hundred three thousand, nineteen” in standard form.', '603,019', '630,019', '603,190', '6,030,019'],
  ['What digit is in the hundreds place in 945,382?', '3', '8', '5', '2'],
  ['Which expanded form equals 408,207?', '400,000 + 8,000 + 200 + 7', '400,000 + 80,000 + 200 + 7', '40,000 + 8,000 + 200 + 7', '400,000 + 8,000 + 20 + 7'],
  ['Which number is greatest?', '561,902', '561,290', '516,902', '561,092'],
  ['In 731,458, the 1 has what value?', '1,000', '100', '10,000', '1'],
  ['What number is 9 hundred-thousands, 2 thousands, and 6 ones?', '902,006', '920,006', '902,060', '900,206'],
  ['Which comparison is true?', '498,201 > 489,999', '498,201 < 489,999', '498,201 = 489,999', '498,201 > 498,210'],
  ['A digit moves from the thousands place to the ten-thousands place. Its value becomes how many times greater?', '10 times', '2 times', '100 times', '1/10 as great']
];

let state = { subject: 'math', grade: 4, chapter: null, concept: null, question: 0, attempts: 0, answers: {}, sparks: Number(localStorage.getItem('numberQuestSparks') || 0), started: JSON.parse(localStorage.getItem('numberQuestStarted') || '[]'), trophies: JSON.parse(localStorage.getItem('numberQuestTrophies') || '[]') };
const $ = selector => document.querySelector(selector);
function save() { localStorage.setItem('numberQuestSparks', state.sparks); localStorage.setItem('numberQuestStarted', JSON.stringify(state.started)); localStorage.setItem('numberQuestTrophies', JSON.stringify(state.trophies)); }
const subjects = [
  { id: 'math', name: 'Mathematics', symbol: '∑', blurb: 'Numbers, shapes, and problem solving', grades: [4, 5] },
  { id: 'science', name: 'Science', symbol: '⚛', blurb: 'Investigate how the world works', grades: [] },
  { id: 'ela', name: 'Reading & Writing', symbol: '✎', blurb: 'Stories, words, and clear ideas', grades: [] },
  { id: 'social', name: 'Social Studies', symbol: '◍', blurb: 'People, places, and history', grades: [] }
];
const ALL_GRADES = ['K', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const subjectContent = { math: course };
function subjectById(id) { return subjects.find(item => item.id === id); }
function chaptersFor(subject, grade) { const content = subjectContent[subject]; return content && content[grade] ? content[grade].chapters : null; }
function gradeLabel(grade) { return grade == null ? '' : grade === 'K' ? 'Kindergarten' : `Grade ${grade}`; }
function currentChapter() { return chaptersFor(state.subject, state.grade)[state.chapter]; }
function missionKey() { return `${state.subject}-${state.grade}-${state.chapter}-${state.concept}`; }
function genericQuestions() { const items = questionSets[state.grade][state.chapter].filter(item => item.concept === state.concept); const base = items.length ? items : questionSets[state.grade][state.chapter]; return Array.from({ length: 10 }, (_, index) => { const item = base[index % base.length]; return { question: item[0], correct: item[1], options: item.slice(1), id: index }; }); }
function currentQuestions() { return state.subject === 'math' && state.grade === 4 && state.chapter === 0 && state.concept === 0 ? placeValueQuestions.map(item => ({ question:item[0], correct:item[1], options:item.slice(1), id:item.id })) : genericQuestions(); }
function currentQuestion() { return currentQuestions()[state.question]; }
function subjectHasContent(id, grade) { return !!chaptersFor(id, grade); }
function gradeHasContent(grade) { return subjects.some(subject => chaptersFor(subject.id, grade)); }
function renderGradeRail() {
  $('#gradeRail').innerHTML = ALL_GRADES.map(grade => { const active = gradeHasContent(grade); return `<button class="grade-chip ${grade === state.grade ? 'active' : ''} ${active ? '' : 'soon'}" data-grade="${grade}" ${active ? '' : 'disabled'}>${grade === 'K' ? 'K' : 'Gr ' + grade}</button>`; }).join('');
  document.querySelectorAll('[data-grade]').forEach(button => button.addEventListener('click', () => {
    if (button.disabled) return;
    state.grade = button.dataset.grade === 'K' ? 'K' : Number(button.dataset.grade);
    if (!subjectHasContent(state.subject, state.grade)) state.subject = (subjects.find(subject => chaptersFor(subject.id, state.grade)) || {}).id || null;
    resetToChapters(); renderGradeRail(); renderSubjectTabs(); renderChapters();
  }));
}
function renderSubjectTabs() {
  $('#subjectTabs').innerHTML = subjects.map(subject => { const available = subjectHasContent(subject.id, state.grade); return `<button class="subject-tab ${subject.id === state.subject ? 'active' : ''} ${available ? '' : 'soon'}" data-subject="${subject.id}" ${available ? '' : 'disabled'}><span class="subject-symbol">${subject.symbol}</span><span class="subject-text"><strong>${subject.name}</strong><small>${available ? subject.blurb : 'Coming soon'}</small></span></button>`; }).join('');
  document.querySelectorAll('[data-subject]').forEach(button => button.addEventListener('click', () => { if (button.disabled) return; selectSubject(button.dataset.subject); }));
}
function selectSubject(id) { if (!subjectHasContent(id, state.grade)) return; state.subject = id; resetToChapters(); renderSubjectTabs(); renderChapters(); }
function resetToChapters() { state.chapter = null; state.concept = null; $('#emptyState').hidden = false; $('#lessonView').hidden = true; }
function renderChapters() {
  const subject = subjectById(state.subject), chapters = chaptersFor(state.subject, state.grade), label = gradeLabel(state.grade);
  $('#chapterHeading').textContent = `${subject.name}${label ? ' · ' + label : ''}`;
  if (!chapters) {
    $('#emptyState').hidden = true; $('#lessonView').hidden = true; $('#chapterProgress').textContent = '';
    $('#chapterGrid').innerHTML = `<div class="coming-soon"><div class="soon-badge">Coming soon</div><h3>${subject.name}${label ? ' · ' + label : ''} is on the way</h3><p>We are building the platform in phases. Mathematics for Grade 4 and Grade 5 is ready now — choose it from the subject bar to start practicing.</p></div>`;
    return;
  }
  const prefix = `${state.subject}-${state.grade}-`;
  $('#chapterGrid').innerHTML = chapters.map((chapter, index) => `<button class="chapter-card ${state.started.includes(prefix + index) ? 'started' : ''}" data-chapter="${index}"><span class="chapter-number">${index + 1}</span><h3>${chapter[0]}</h3><p>${chapter[1].join(' · ')}</p></button>`).join('');
  $('#chapterProgress').textContent = `${state.started.filter(item => item.startsWith(prefix)).length} of ${chapters.length} chapters started`;
  document.querySelectorAll('[data-chapter]').forEach(button => button.addEventListener('click', () => startChapter(Number(button.dataset.chapter))));
}
const conceptLessons = {
  'Place value': ['A digit’s place tells its value. In 582,641, the 8 is in the ten-thousands place, so it means 80,000, not 8.', 'Example: moving a 6 from the hundreds place to the thousands place changes its value from 600 to 6,000.', 'Remember: each step left is 10 times greater; each step right is 10 times smaller.', 'grid'],
  'Rounding': ['Rounding gives a nearby, friendly number for estimating. Find the place you are rounding to, then inspect the digit immediately to its right.', 'Example: 386,749 rounded to the nearest thousand is 387,000 because the hundreds digit is 7.', 'Remember: 5 or more rounds up; 4 or less stays down.', 'grid'],
  'Add & subtract': ['Line up digits by place value so ones are under ones, tens under tens, and so on. Regroup when a column needs more or fewer units.', 'Example: in 4,786 + 2,549, 6 + 9 makes 15 ones. Write 5 ones and regroup 1 ten.', 'Remember: check subtraction by adding the difference and the number taken away.', 'grid'],
  'Arrays': ['An array organizes equal groups into rows and columns. It shows why multiplication is a fast way to count equal groups.', 'Example: 3 rows of 4 dots is 3 x 4 = 12 dots.', 'Remember: rows x columns and columns x rows give the same total.', 'dots'],
  'Area models': ['An area model splits a harder multiplication into smaller rectangles. Break a factor into tens and ones, solve each part, then add.', 'Example: 23 x 4 = (20 x 4) + (3 x 4) = 80 + 12 = 92.', 'Remember: include every partial product before adding.', 'dots'],
  'Multi-digit products': ['For multi-digit multiplication, each digit represents a place value. Multiply one place at a time and regroup when needed.', 'Example: 1,426 x 3 is 4,278. Estimate first: 1,400 x 3 is about 4,200, so the answer is reasonable.', 'Remember: a digit in the tens place represents tens, not ones.', 'dots'],
  'Equal groups': ['Division shares a total into equal groups. The dividend is what is shared, the divisor tells the number of groups, and the quotient tells the amount in each group.', 'Example: 84 divided by 6 = 14 means 84 objects make 6 equal groups of 14.', 'Remember: check with divisor x quotient = dividend.', 'dots'],
  'Long division': ['Long division works one place at a time: divide, multiply, subtract, then bring down the next digit.', 'Example: for 864 divided by 4, divide 8 hundreds, then 6 tens, then 4 ones to get 216.', 'Remember: place every quotient digit directly above the digit you divided.', 'lines'],
  'Remainders': ['A remainder is what is left after making equal groups. The context tells you whether to keep it, round up, or ignore it.', 'Example: 29 students in vans of 6 need 5 vans: 29 divided by 6 is 4 remainder 5, and the five students still need a van.', 'Remember: a remainder must always be smaller than the divisor.', 'lines'],
  'Multi-step plans': ['Multi-step problems need more than one operation. Identify what happens first, solve it, and use that answer in the next step.', 'Example: 6 boxes with 24 pencils each, then 17 given away: multiply 6 x 24, then subtract 17.', 'Remember: write a short equation for each step and label the final answer.', 'grid'],
  'Variables': ['A variable is a letter that stands for an unknown number. An equation says the two sides have the same value.', 'Example: n + 36 = 91. Subtract 36 from both sides, so n = 55.', 'Remember: use the inverse operation to undo what happened to the variable.', 'grid'],
  'Factors': ['Factors are whole numbers that multiply to make a product. Multiples are the products made when you multiply a number by whole numbers.', 'Example: factor pairs of 24 include 1 x 24, 2 x 12, 3 x 8, and 4 x 6.', 'Remember: a prime number has exactly two factors; 1 is neither prime nor composite.', 'grid'],
  'Unit conversions': ['A conversion changes the unit name without changing the amount. Start by writing the fact that connects the units.', 'Example: 4 feet x 12 inches per foot = 48 inches.', 'Remember: changing from a larger unit to a smaller unit makes the number larger.', 'lines'],
  'Time and volume': ['Measurement facts connect time, capacity, mass, and length. Choose the conversion that matches the unit in the question.', 'Example: 3 kilograms equals 3,000 grams because each kilogram has 1,000 grams.', 'Remember: write units beside every number so you know what is being counted.', 'lines'],
  'Area & perimeter': ['Perimeter measures the distance around a shape. Area measures the square units covering the inside.', 'Example: a 7 m by 4 m rectangle has perimeter 7 + 4 + 7 + 4 = 22 m and area 7 x 4 = 28 square m.', 'Remember: perimeter uses regular units; area uses square units.', 'lines'],
  'Equivalent fractions': ['Equivalent fractions name the same amount, even though their numbers look different. Multiply or divide the top and bottom by the same number.', 'Example: 1/2 = 2/4 because both numerator and denominator were multiplied by 2.', 'Remember: whatever happens to the numerator must also happen to the denominator.', 'fraction'],
  'Adding fractions': ['Fractions can be added when the denominators match because the pieces are the same size. Add only the numerators.', 'Example: 3/8 + 2/8 = 5/8.', 'Remember: keep the denominator; it tells the size of each piece.', 'fraction'],
  'Subtracting fractions': ['Fractions with matching denominators can be subtracted by taking away the numerators.', 'Example: 7/10 - 3/10 = 4/10, which simplifies to 2/5.', 'Remember: simplify the final fraction when top and bottom share a factor.', 'fraction'],
  'Fraction groups': ['Multiplying a whole number by a fraction means taking repeated groups of that fraction.', 'Example: 3 x 2/5 = 6/5 = 1 1/5.', 'Remember: multiply the whole number by the numerator, then simplify or make a mixed number.', 'fraction'],
  'Tenths & hundredths': ['Decimals are another way to name parts of one whole. The first place after the decimal is tenths, and the second is hundredths.', 'Example: 0.7 means 7/10, while 0.35 means 35/100.', 'Remember: add zeros when comparing, so 0.7 can be written as 0.70.', 'grid'],
  'Compare decimals': ['Compare decimals from left to right, just as you compare whole numbers. Make both numbers have the same number of decimal places first.', 'Example: 0.75 is greater than 0.70 because 75 hundredths is greater than 70 hundredths.', 'Remember: a zero added to the right of a decimal does not change its value.', 'grid'],
  'Lines': ['A line continues forever in both directions, a segment has two endpoints, and a ray begins at one endpoint and continues forever in one direction.', 'Example: railroad tracks are parallel because they never meet; a corner of paper shows perpendicular lines because they meet at a right angle.', 'Remember: look for endpoints and arrowheads to name the figure.', 'lines'],
  'Angles': ['An angle measures a turn between two rays. Its size depends on the opening, not on how long the rays are.', 'Example: 45 degrees is acute, 90 degrees is right, and 120 degrees is obtuse.', 'Remember: compare the opening with a square corner to recognize a right angle.', 'lines'],
  'Symmetry': ['A line of symmetry splits a shape into two matching mirror-image halves. Folding on that line would make the halves match exactly.', 'Example: a square has four lines of symmetry, while a scalene triangle has none.', 'Remember: both sides of a symmetry line must match in size and shape.', 'lines'],
  'Equal groups': ['Equal groups show multiplication or division clearly. Count how many groups there are and how many items are in each.', 'Example: 4 groups of 7 makes 4 x 7 = 28.', 'Remember: multiplication combines equal groups; division shares into equal groups.', 'dots'],
  'Expressions': ['An expression is a math phrase without an equals sign. Parentheses tell you to calculate the inside part first.', 'Example: (8 + 2) x 5 = 10 x 5 = 50.', 'Remember: solve inside parentheses before multiplying or dividing.', 'grid'],
  'Perimeter': ['Perimeter is the distance around the outside edge of a shape. Add all of its side lengths.', 'Example: a 6 by 4 rectangle has perimeter 6 + 4 + 6 + 4 = 20 units.', 'Remember: walk around the shape once and count every side.', 'lines'],
  'Area': ['Area is the flat space inside a shape, measured in square units. A rectangle’s area is length x width.', 'Example: a 6 by 4 rectangle covers 24 square units.', 'Remember: area tiles cover the inside; perimeter traces the outside.', 'lines'],
  'Whole numbers': ['Whole-number addition and subtraction use place value. Arrange numbers vertically and keep each column lined up.', 'Example: 47,891 + 23,109 = 71,000 because the ones, tens, hundreds, and thousands are added in matching columns.', 'Remember: regroup carefully and estimate to check your answer.', 'grid'],
  'Decimals': ['For decimal operations, line up decimal points first so tenths meet tenths and hundredths meet hundredths.', 'Example: 3.40 + 0.65 = 4.05.', 'Remember: zero is a useful placeholder, but never move the decimal point.', 'grid'],
  'Straight lines': ['A straight angle makes a half-turn and measures 180 degrees. Two angles beside each other on a straight line must add to 180.', 'Example: if one angle is 70 degrees, the other is 110 degrees.', 'Remember: check that the pair totals exactly 180 degrees.', 'lines'],
  'Polygons': ['A polygon is a closed, flat shape made only from straight line segments. Its name often tells how many sides it has.', 'Example: a hexagon has 6 sides and 6 vertices.', 'Remember: curved sides or an open gap mean the shape is not a polygon.', 'lines'],
  'Addition': ['To add fractions, rewrite them with a common denominator so all pieces are the same size.', 'Example: 1/3 + 1/6 becomes 2/6 + 1/6 = 3/6 = 1/2.', 'Remember: add numerators only after the denominators match.', 'fraction'],
  'Subtraction': ['To subtract fractions with unlike denominators, rename them using a common denominator first.', 'Example: 3/4 - 1/4 = 2/4 = 1/2.', 'Remember: subtract numerators only when the pieces are the same size.', 'fraction'],
  'Volume': ['Volume counts the cubic units filling a solid box. A rectangular prism has length, width, and height.', 'Example: 4 x 3 x 2 = 24 cubic units.', 'Remember: volume uses three measurements and cubic units.', 'grid'],
  'Conversions': ['Measurement conversions use known unit relationships. Decide whether you are changing to a bigger or smaller unit.', 'Example: 3 feet = 36 inches because 3 x 12 = 36.', 'Remember: use a conversion fact before calculating.', 'lines'],
  'Layers': ['A rectangular prism is built from equal layers of unit cubes. Find the cubes in one layer, then multiply by the number of layers.', 'Example: 12 cubes in each layer x 3 layers = 36 cubic units.', 'Remember: each layer must contain the same number of cubes.', 'grid'],
  'Integers': ['Integers include positive numbers, negative numbers, and zero. A number line shows their order.', 'Example: -3 is three steps left of zero, while 4 is four steps right of zero.', 'Remember: numbers farther right are greater.', 'lines'],
  'Absolute value': ['Absolute value is a number’s distance from zero, so it is never negative.', 'Example: |-5| = 5 because -5 is five steps away from zero.', 'Remember: the bars mean distance, not a negative sign.', 'lines'],
  'Coordinate plane': ['A coordinate plane uses a horizontal x-axis and vertical y-axis. Read an ordered pair x first, then y.', 'Example: to plot (3, -2), move 3 right and then 2 down.', 'Remember: begin every point at the origin, (0, 0).', 'lines'],
  'Fraction multiplication': ['Multiplying a fraction by a whole number is repeated groups of that fraction.', 'Example: 3/4 x 4 = 12/4 = 3.', 'Remember: simplify after multiplying and change improper fractions to mixed numbers when helpful.', 'fraction'],
  'Decimal operations': ['Decimal multiplication and division use place value. Estimate first, then place the decimal so the result makes sense.', 'Example: 2.4 divided by 0.3 = 8 because 24 tenths divided by 3 tenths equals 8.', 'Remember: an estimate catches a misplaced decimal point.', 'grid']
};
function lessonForConcept(concept, chapterLesson) { const lesson = conceptLessons[concept]; return lesson ? `<p class="lesson-copy"><strong>What it means:</strong> ${lesson[0]}</p><p class="lesson-copy"><strong>${lesson[1]}</strong></p><p class="lesson-copy"><strong>Remember:</strong> ${lesson[2].replace(/^Remember:\s*/, '')}</p>` : `<p class="lesson-copy"><strong>${concept}:</strong> ${chapterLesson}</p>`; }
const C = { navy: '#0B3954', teal: '#007C91', gold: '#F4B942', coral: '#FF876C', mint: '#57C9AE', sky: '#5AA9E6', lime: '#9BC53D', ink: '#173042', paper: '#ffffff' };
function fig(caption, inner, h = 158) { return `<figure class="concept-figure"><svg viewBox="0 0 440 ${h}" role="img" aria-label="${caption}"><rect x="1" y="1" width="438" height="${h - 2}" rx="12" fill="#eef7f4" stroke="#cfe6df"/>${inner}</svg><figcaption>${caption}</figcaption></figure>`; }
function dots(x, y, cols, rows, gap, r, fill) { let out = ''; for (let row = 0; row < rows; row++) for (let col = 0; col < cols; col++) out += `<circle cx="${x + col * gap}" cy="${y + row * gap}" r="${r}" fill="${fill}" stroke="${C.ink}" stroke-width="1"/>`; return out; }
function conceptVisuals() {
  return {
    'Rounding': fig('Round down or up by the next digit', `<text x="22" y="24" font-size="11" font-weight="bold" fill="${C.navy}">Nearest thousand — check the hundreds digit</text><text x="22" y="48" font-size="12" font-weight="bold" fill="${C.coral}">386,499 → 386,000  (hundreds digit 4, round DOWN)</text><line x1="35" y1="72" x2="405" y2="72" stroke="${C.navy}" stroke-width="2"/><line x1="35" y1="66" x2="35" y2="78" stroke="${C.navy}" stroke-width="2"/><line x1="220" y1="66" x2="220" y2="78" stroke="#9fb3ad"/><line x1="405" y1="66" x2="405" y2="78" stroke="${C.navy}" stroke-width="2"/><text x="20" y="92" font-size="9" fill="${C.navy}">386,000</text><text x="200" y="92" font-size="9" fill="#5c7168">386,500</text><text x="378" y="92" font-size="9" fill="${C.navy}">387,000</text><circle cx="182" cy="72" r="6" fill="${C.coral}" stroke="${C.ink}"/><path d="M176 64 Q108 46 42 66" fill="none" stroke="${C.coral}" stroke-width="2.5"/><polygon points="40,66 51,61 50,71" fill="${C.coral}"/><text x="22" y="128" font-size="12" font-weight="bold" fill="${C.teal}">386,749 → 387,000  (hundreds digit 7, round UP)</text><line x1="35" y1="152" x2="405" y2="152" stroke="${C.navy}" stroke-width="2"/><line x1="35" y1="146" x2="35" y2="158" stroke="${C.navy}" stroke-width="2"/><line x1="220" y1="146" x2="220" y2="158" stroke="#9fb3ad"/><line x1="405" y1="146" x2="405" y2="158" stroke="${C.navy}" stroke-width="2"/><text x="20" y="172" font-size="9" fill="${C.navy}">386,000</text><text x="200" y="172" font-size="9" fill="#5c7168">386,500</text><text x="378" y="172" font-size="9" fill="${C.navy}">387,000</text><circle cx="316" cy="152" r="6" fill="${C.teal}" stroke="${C.ink}"/><path d="M322 144 Q372 124 402 146" fill="none" stroke="${C.teal}" stroke-width="2.5"/><polygon points="404,150 393,142 399,154" fill="${C.teal}"/><text x="22" y="200" font-size="11" font-weight="bold" fill="${C.ink}">Rule: hundreds digit 0–4 stays · 5–9 rounds up (386,500 rounds up)</text>`, 212),
    'Add & subtract': fig('Line up places and regroup', `<text x="150" y="44" font-size="13" fill="${C.coral}" font-weight="bold">1</text><text x="120" y="66" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">4,786</text><text x="110" y="96" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">+ 2,549</text><line x1="108" y1="106" x2="250" y2="106" stroke="${C.teal}" stroke-width="2.5"/><text x="120" y="134" font-size="24" font-family="Arial" font-weight="bold" fill="${C.teal}">7,335</text><text x="300" y="74" font-size="12" fill="${C.ink}">6 + 9 = 15</text><text x="300" y="96" font-size="12" fill="${C.ink}">write 5,</text><text x="300" y="114" font-size="12" fill="${C.ink}">carry 1 ten</text>`),
    'Arrays': fig('3 rows × 4 columns = 12', `${dots(96, 50, 4, 3, 32, 11, C.mint)}<text x="92" y="34" font-size="11" font-weight="bold" fill="${C.navy}">4 columns →</text><text x="44" y="96" font-size="11" font-weight="bold" fill="${C.navy}" transform="rotate(-90 44 96)">3 rows</text><text x="250" y="78" font-size="20" font-weight="bold" fill="${C.teal}">3 × 4 = 12</text><text x="250" y="104" font-size="12" fill="${C.ink}">count by rows or columns</text>`),
    'Area models': fig('23 × 4 = 80 + 12 = 92', `<rect x="60" y="52" width="210" height="60" fill="#fff" stroke="${C.teal}" stroke-width="2"/><line x1="216" y1="52" x2="216" y2="112" stroke="${C.teal}" stroke-width="2"/><text x="130" y="46" font-size="12" fill="${C.navy}">20</text><text x="230" y="46" font-size="12" fill="${C.navy}">3</text><text x="40" y="88" font-size="12" fill="${C.navy}">4</text><text x="118" y="88" font-size="20" font-weight="bold" fill="${C.teal}">80</text><text x="228" y="88" font-size="18" font-weight="bold" fill="${C.coral}">12</text><text x="300" y="88" font-size="16" font-weight="bold" fill="${C.navy}">= 92</text>`),
    'Multi-digit products': fig('1,426 × 3 = 4,278', `<text x="150" y="60" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">1,426</text><text x="158" y="90" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">×   3</text><line x1="150" y1="100" x2="270" y2="100" stroke="${C.teal}" stroke-width="2.5"/><text x="150" y="128" font-size="24" font-family="Arial" font-weight="bold" fill="${C.teal}">4,278</text><text x="300" y="86" font-size="12" fill="${C.ink}">estimate:</text><text x="300" y="104" font-size="12" fill="${C.ink}">≈ 4,200</text>`),
    'Equal groups': fig('84 shared into 6 equal groups of 14', `${[0,1,2,3,4,5].map(i => `<rect x="${40 + i * 62}" y="54" width="48" height="44" rx="7" fill="${C.sky}" stroke="${C.navy}" stroke-width="1.5"/><text x="${52 + i * 62}" y="82" font-size="16" font-weight="bold" fill="#fff">14</text>`).join('')}<text x="120" y="126" font-size="14" font-weight="bold" fill="${C.navy}">6 × 14 = 84</text>`),
    'Long division': fig('864 ÷ 4 = 216', `<text x="150" y="70" font-size="16" fill="${C.teal}" font-weight="bold">2  1  6</text><path d="M120 78 h150" stroke="${C.navy}" stroke-width="2"/><text x="95" y="96" font-size="26" font-family="Arial" font-weight="bold" fill="${C.navy}">4</text><path d="M118 74 q10 20 0 40" fill="none" stroke="${C.navy}" stroke-width="2"/><text x="128" y="98" font-size="26" font-family="Arial" font-weight="bold" fill="${C.navy}">864</text><text x="300" y="82" font-size="12" fill="${C.ink}">divide, multiply,</text><text x="300" y="100" font-size="12" fill="${C.ink}">subtract, bring down</text>`),
    'Remainders': fig('29 ÷ 6 = 4 remainder 5', `${[0,1,2,3].map(i => `<rect x="${40 + i * 56}" y="52" width="44" height="40" rx="6" fill="${C.mint}" stroke="${C.navy}"/><text x="${52 + i * 56}" y="78" font-size="15" font-weight="bold" fill="#fff">6</text>`).join('')}<rect x="272" y="52" width="44" height="40" rx="6" fill="${C.coral}" stroke="${C.navy}"/><text x="288" y="78" font-size="15" font-weight="bold" fill="#fff">5</text><text x="60" y="120" font-size="13" font-weight="bold" fill="${C.navy}">4 full groups, remainder 5</text>`),
    'Multi-step plans': fig('6 × 24 = 144, then 144 − 17 = 127', `<rect x="30" y="60" width="110" height="40" rx="8" fill="#fff" stroke="${C.teal}" stroke-width="2"/><text x="42" y="85" font-size="14" font-weight="bold" fill="${C.navy}">6 × 24 = 144</text><path d="M145 80 h40" stroke="${C.navy}" stroke-width="2"/><polygon points="187,80 177,75 177,85" fill="${C.navy}"/><rect x="190" y="60" width="120" height="40" rx="8" fill="#fff" stroke="${C.teal}" stroke-width="2"/><text x="200" y="85" font-size="14" font-weight="bold" fill="${C.navy}">144 − 17 = 127</text><path d="M315 80 h30" stroke="${C.navy}" stroke-width="2"/><polygon points="347,80 337,75 337,85" fill="${C.navy}"/><text x="352" y="86" font-size="18" font-weight="bold" fill="${C.teal}">127</text>`),
    'Variables': fig('n + 36 = 91, so n = 55', `<line x1="80" y1="112" x2="360" y2="112" stroke="${C.navy}" stroke-width="3"/><polygon points="220,70 205,100 235,100" fill="${C.gold}" stroke="${C.ink}"/><rect x="120" y="76" width="60" height="26" rx="6" fill="${C.mint}" stroke="${C.navy}"/><text x="138" y="95" font-size="15" font-weight="bold" fill="#fff">n+36</text><rect x="262" y="76" width="52" height="26" rx="6" fill="${C.sky}" stroke="${C.navy}"/><text x="278" y="95" font-size="15" font-weight="bold" fill="#fff">91</text><text x="150" y="140" font-size="13" font-weight="bold" fill="${C.teal}">91 − 36 = 55</text>`),
    'Factors': fig('Factor pairs of 24', `${[['1 × 24',40],['2 × 12',150],['3 × 8',260],['4 × 6',350]].map(([t,x]) => `<rect x="${x}" y="58" width="72" height="34" rx="7" fill="${C.sky}" stroke="${C.navy}"/><text x="${x+10}" y="80" font-size="13" font-weight="bold" fill="#fff">${t}</text>`).join('')}<text x="120" y="124" font-size="13" font-weight="bold" fill="${C.navy}">Each pair multiplies to 24</text>`),
    'Unit conversions': fig('4 feet = 48 inches', `<rect x="40" y="60" width="360" height="26" fill="#fff" stroke="${C.navy}"/>${[0,1,2,3].map(i => `<line x1="${40 + i * 90}" y1="60" x2="${40 + i * 90}" y2="86" stroke="${C.teal}" stroke-width="2"/><text x="${64 + i * 90}" y="104" font-size="11" fill="${C.navy}">1 ft</text>`).join('')}<text x="120" y="46" font-size="14" font-weight="bold" fill="${C.teal}">4 ft × 12 = 48 inches</text><text x="150" y="130" font-size="12" fill="${C.ink}">smaller unit → bigger number</text>`),
    'Time and volume': fig('3 kilograms = 3,000 grams', `<circle cx="120" cy="80" r="44" fill="#fff" stroke="${C.navy}" stroke-width="2"/><line x1="120" y1="80" x2="120" y2="44" stroke="${C.coral}" stroke-width="3"/><text x="98" y="140" font-size="13" font-weight="bold" fill="${C.navy}">3 kg</text><text x="210" y="76" font-size="16" font-weight="bold" fill="${C.teal}">× 1,000</text><text x="210" y="104" font-size="16" font-weight="bold" fill="${C.navy}">= 3,000 g</text>`),
    'Area & perimeter': fig('7 × 4 rectangle: area 28, perimeter 22', `<rect x="120" y="46" width="200" height="66" fill="#eafaf4" stroke="${C.teal}" stroke-width="3"/><text x="205" y="40" font-size="13" font-weight="bold" fill="${C.navy}">7 m</text><text x="326" y="84" font-size="13" font-weight="bold" fill="${C.navy}">4 m</text><text x="150" y="86" font-size="15" font-weight="bold" fill="${C.teal}">Area = 28</text><text x="120" y="138" font-size="13" fill="${C.ink}">Perimeter = 7+4+7+4 = 22 m</text>`),
    'Equivalent fractions': fig('1/2 = 2/4 (same amount)', `<rect x="60" y="46" width="200" height="30" fill="#fff" stroke="${C.navy}"/><rect x="60" y="46" width="100" height="30" fill="${C.gold}" stroke="${C.navy}"/><text x="270" y="68" font-size="16" font-weight="bold" fill="${C.navy}">1/2</text><rect x="60" y="92" width="200" height="30" fill="#fff" stroke="${C.navy}"/><rect x="60" y="92" width="100" height="30" fill="${C.gold}" stroke="${C.navy}"/><line x1="110" y1="92" x2="110" y2="122" stroke="${C.navy}"/><line x1="210" y1="92" x2="210" y2="122" stroke="${C.navy}"/><text x="270" y="114" font-size="16" font-weight="bold" fill="${C.navy}">2/4</text>`),
    'Adding fractions': fig('3/8 + 2/8 = 5/8', `<rect x="50" y="58" width="320" height="34" fill="#fff" stroke="${C.navy}"/>${[0,1,2,3,4,5,6,7].map(i => `<line x1="${50 + i * 40}" y1="58" x2="${50 + i * 40}" y2="92" stroke="${C.navy}"/>`).join('')}${[0,1,2].map(i => `<rect x="${50 + i * 40}" y="58" width="40" height="34" fill="${C.mint}"/>`).join('')}${[3,4].map(i => `<rect x="${50 + i * 40}" y="58" width="40" height="34" fill="${C.gold}"/>`).join('')}<text x="150" y="122" font-size="15" font-weight="bold" fill="${C.navy}">3 eighths + 2 eighths = 5/8</text>`),
    'Subtracting fractions': fig('7/10 − 3/10 = 4/10', `<rect x="40" y="58" width="360" height="34" fill="#fff" stroke="${C.navy}"/>${Array.from({length:10}).map((_,i) => `<line x1="${40 + i * 36}" y1="58" x2="${40 + i * 36}" y2="92" stroke="${C.navy}"/>`).join('')}${[0,1,2,3].map(i => `<rect x="${40 + i * 36}" y="58" width="36" height="34" fill="${C.sky}"/>`).join('')}${[4,5,6].map(i => `<rect x="${40 + i * 36}" y="58" width="36" height="34" fill="#f2c9c0"/><line x1="${40 + i * 36}" y1="58" x2="${76 + i * 36}" y2="92" stroke="${C.coral}"/>`).join('')}<text x="120" y="122" font-size="14" font-weight="bold" fill="${C.navy}">take away 3, keep 4/10</text>`),
    'Fraction groups': fig('3 × 2/5 = 6/5 = 1 1/5', `${[0,1,2].map(g => `<rect x="${40 + g * 130}" y="56" width="100" height="30" fill="#fff" stroke="${C.navy}"/>${[0,1].map(i => `<rect x="${40 + g * 130 + i * 20}" y="56" width="20" height="30" fill="${C.gold}"/>`).join('')}${[2,3,4].map(i => `<line x1="${40 + g * 130 + i * 20}" y1="56" x2="${40 + g * 130 + i * 20}" y2="86" stroke="${C.navy}"/>`).join('')}<text x="${72 + g * 130}" y="106" font-size="12" fill="${C.navy}">2/5</text>`).join('')}<text x="150" y="134" font-size="13" font-weight="bold" fill="${C.teal}">3 groups of 2/5 = 6/5</text>`),
    'Tenths & hundredths': fig('0.7 = 7/10 and 0.35 = 35/100', `<rect x="40" y="42" width="150" height="30" fill="#fff" stroke="${C.navy}"/>${Array.from({length:10}).map((_,i) => `<rect x="${40 + i * 15}" y="42" width="15" height="30" fill="${i < 7 ? C.mint : '#fff'}" stroke="${C.navy}"/>`).join('')}<text x="200" y="64" font-size="14" font-weight="bold" fill="${C.navy}">0.7 = 7/10</text><g>${Array.from({length:100}).map((_,i) => `<rect x="${40 + (i % 10) * 8}" y="${86 + Math.floor(i / 10) * 6}" width="8" height="6" fill="${i < 35 ? C.gold : '#fff'}" stroke="#ccd"/>`).join('')}</g><text x="200" y="118" font-size="14" font-weight="bold" fill="${C.navy}">0.35 = 35/100</text>`),
    'Compare decimals': fig('0.75 > 0.70', `<rect x="50" y="50" width="150" height="28" fill="#fff" stroke="${C.navy}"/><rect x="50" y="50" width="112" height="28" fill="${C.mint}"/><text x="90" y="98" font-size="15" font-weight="bold" fill="${C.navy}">0.75</text><text x="212" y="74" font-size="30" font-weight="bold" fill="${C.coral}">&gt;</text><rect x="250" y="50" width="150" height="28" fill="#fff" stroke="${C.navy}"/><rect x="250" y="50" width="105" height="28" fill="${C.sky}"/><text x="292" y="98" font-size="15" font-weight="bold" fill="${C.navy}">0.70</text><text x="120" y="132" font-size="12" fill="${C.ink}">75 hundredths beats 70 hundredths</text>`),
    'Lines': fig('Parallel and perpendicular lines', `<line x1="40" y1="58" x2="180" y2="58" stroke="${C.teal}" stroke-width="3"/><line x1="40" y1="92" x2="180" y2="92" stroke="${C.teal}" stroke-width="3"/><text x="66" y="118" font-size="12" font-weight="bold" fill="${C.navy}">parallel</text><line x1="300" y1="40" x2="300" y2="110" stroke="${C.navy}" stroke-width="3"/><line x1="255" y1="86" x2="360" y2="86" stroke="${C.navy}" stroke-width="3"/><rect x="300" y="76" width="10" height="10" fill="none" stroke="${C.coral}" stroke-width="2"/><text x="252" y="128" font-size="12" font-weight="bold" fill="${C.navy}">perpendicular</text>`),
    'Angles': fig('Acute (45°), right (90°), and obtuse (120°)', `<line x1="55" y1="104" x2="55" y2="50" stroke="${C.navy}" stroke-width="2.5"/><line x1="55" y1="104" x2="102" y2="75" stroke="${C.teal}" stroke-width="2.5"/><path d="M55 84 A20 20 0 0 1 73 94" fill="none" stroke="${C.gold}" stroke-width="2"/><text x="62" y="72" font-size="11" font-weight="bold" fill="${C.teal}">45°</text><text x="36" y="126" font-size="11" fill="${C.navy}">acute</text><line x1="195" y1="104" x2="195" y2="50" stroke="${C.navy}" stroke-width="2.5"/><line x1="195" y1="104" x2="248" y2="104" stroke="${C.navy}" stroke-width="2.5"/><rect x="195" y="92" width="12" height="12" fill="none" stroke="${C.coral}" stroke-width="2"/><text x="212" y="84" font-size="11" font-weight="bold" fill="${C.coral}">90°</text><text x="188" y="126" font-size="11" fill="${C.navy}">right</text><line x1="340" y1="104" x2="340" y2="50" stroke="${C.navy}" stroke-width="2.5"/><line x1="340" y1="104" x2="400" y2="122" stroke="${C.gold}" stroke-width="2.5"/><path d="M340 78 A26 26 0 0 1 360 100" fill="none" stroke="${C.coral}" stroke-width="2"/><text x="346" y="72" font-size="11" font-weight="bold" fill="${C.gold}">120°</text><text x="330" y="138" font-size="11" fill="${C.navy}">obtuse</text>`),
    'Symmetry': fig('A line of symmetry makes matching halves', `<line x1="220" y1="34" x2="220" y2="124" stroke="${C.coral}" stroke-width="2" stroke-dasharray="5 4"/><polygon points="220,44 150,80 175,116 220,104" fill="${C.sky}" stroke="${C.navy}"/><polygon points="220,44 290,80 265,116 220,104" fill="${C.mint}" stroke="${C.navy}"/><text x="140" y="140" font-size="12" fill="${C.ink}">both sides match when folded</text>`),
    'Expressions': fig('(8 + 2) × 5 = 50', `<rect x="70" y="54" width="90" height="40" rx="8" fill="#fff8e0" stroke="${C.gold}" stroke-width="2"/><text x="82" y="80" font-size="18" font-weight="bold" fill="${C.navy}">8 + 2</text><text x="168" y="80" font-size="18" font-weight="bold" fill="${C.ink}">× 5</text><path d="M115 98 v14 h120" fill="none" stroke="${C.teal}" stroke-width="2"/><text x="245" y="118" font-size="16" font-weight="bold" fill="${C.teal}">10 × 5 = 50</text><text x="70" y="132" font-size="12" fill="${C.ink}">solve inside parentheses first</text>`),
    'Perimeter': fig('Perimeter traces every side', `<rect x="120" y="46" width="200" height="60" fill="none" stroke="${C.coral}" stroke-width="4"/><text x="200" y="40" font-size="12" fill="${C.navy}">6</text><text x="326" y="82" font-size="12" fill="${C.navy}">4</text><text x="120" y="130" font-size="13" font-weight="bold" fill="${C.navy}">6 + 4 + 6 + 4 = 20 units</text>`),
    'Area': fig('Area fills the inside with unit squares', `${Array.from({length:24}).map((_,i) => `<rect x="${130 + (i % 6) * 28}" y="${50 + Math.floor(i / 6) * 18}" width="28" height="18" fill="${C.mint}" stroke="#fff" stroke-width="1"/>`).join('')}<text x="186" y="44" font-size="11" font-weight="bold" fill="${C.navy}">6 units across</text><text x="120" y="96" font-size="11" font-weight="bold" fill="${C.navy}" transform="rotate(-90 120 96)">4 units</text><text x="150" y="140" font-size="13" font-weight="bold" fill="${C.teal}">6 × 4 = 24 square units</text>`),
    'Whole numbers': fig('Add in matching place-value columns', `${['Thousands','Hundreds','Tens','Ones'].map((t,i) => `<rect x="${60 + i * 82}" y="46" width="76" height="24" fill="#fff" stroke="${C.teal}"/><text x="${64 + i * 82}" y="62" font-size="9" font-weight="bold" fill="${C.navy}">${t}</text>`).join('')}<text x="70" y="96" font-size="18" font-weight="bold" fill="${C.navy}">47,891 + 23,109</text><text x="120" y="130" font-size="16" font-weight="bold" fill="${C.teal}">= 71,000</text>`),
    'Decimals': fig('Line up the decimal points', `<text x="150" y="58" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">3.40</text><text x="132" y="88" font-size="24" font-family="Arial" font-weight="bold" fill="${C.navy}">+ 0.65</text><line x1="130" y1="98" x2="240" y2="98" stroke="${C.teal}" stroke-width="2.5"/><text x="150" y="126" font-size="24" font-family="Arial" font-weight="bold" fill="${C.teal}">4.05</text><line x1="196" y1="40" x2="196" y2="130" stroke="${C.coral}" stroke-width="1.5" stroke-dasharray="4 3"/>`),
    'Straight lines': fig('70° + 110° = 180° on a straight line', `<line x1="40" y1="96" x2="400" y2="96" stroke="${C.navy}" stroke-width="3"/><line x1="220" y1="96" x2="150" y2="50" stroke="${C.teal}" stroke-width="3"/><text x="150" y="80" font-size="13" font-weight="bold" fill="${C.teal}">70°</text><text x="250" y="82" font-size="13" font-weight="bold" fill="${C.gold}">110°</text><text x="130" y="128" font-size="13" font-weight="bold" fill="${C.navy}">70 + 110 = 180 degrees</text>`),
    'Polygons': fig('A hexagon has 6 sides and 6 vertices', `<polygon points="220,42 280,68 280,110 220,136 160,110 160,68" fill="${C.sky}" stroke="${C.navy}" stroke-width="2.5"/>${[[220,42],[280,68],[280,110],[220,136],[160,110],[160,68]].map(([x,y]) => `<circle cx="${x}" cy="${y}" r="4" fill="${C.coral}" stroke="${C.ink}"/>`).join('')}<text x="300" y="94" font-size="13" font-weight="bold" fill="${C.navy}">6 sides</text>`),
    'Addition': fig('1/3 + 1/6 = 2/6 + 1/6 = 1/2', `<rect x="50" y="52" width="150" height="30" fill="#fff" stroke="${C.navy}"/><rect x="50" y="52" width="50" height="30" fill="${C.mint}"/><text x="205" y="74" font-size="13" fill="${C.navy}">1/3 = 2/6</text><rect x="50" y="92" width="150" height="30" fill="#fff" stroke="${C.navy}"/><rect x="50" y="92" width="25" height="30" fill="${C.gold}"/><text x="205" y="114" font-size="13" fill="${C.navy}">+ 1/6 → 3/6 = 1/2</text>`),
    'Subtraction': fig('3/4 − 1/4 = 2/4 = 1/2', `<rect x="50" y="56" width="300" height="34" fill="#fff" stroke="${C.navy}"/>${[0,1,2,3].map(i => `<line x1="${50 + i * 75}" y1="56" x2="${50 + i * 75}" y2="90" stroke="${C.navy}"/>`).join('')}${[0,1].map(i => `<rect x="${50 + i * 75}" y="56" width="75" height="34" fill="${C.mint}"/>`).join('')}<rect x="200" y="56" width="75" height="34" fill="#f2c9c0"/><line x1="200" y1="56" x2="275" y2="90" stroke="${C.coral}"/><text x="120" y="120" font-size="14" font-weight="bold" fill="${C.navy}">take away 1/4, keep 2/4</text>`),
    'Volume': fig('4 × 3 × 2 = 24 cubic units', `<polygon points="120,70 240,70 300,46 180,46" fill="${C.sky}" stroke="${C.navy}"/><polygon points="240,70 240,120 300,96 300,46" fill="${C.teal}" stroke="${C.navy}"/><rect x="120" y="70" width="120" height="50" fill="#bfe6f2" stroke="${C.navy}"/><text x="150" y="100" font-size="12" fill="${C.navy}">L 4 × W 3</text><text x="255" y="92" font-size="12" fill="#fff">H 2</text><text x="150" y="142" font-size="13" font-weight="bold" fill="${C.navy}">= 24 cubic units</text>`),
    'Conversions': fig('3 feet = 36 inches', `<rect x="40" y="62" width="330" height="24" fill="#fff" stroke="${C.navy}"/>${[0,1,2].map(i => `<line x1="${40 + i * 110}" y1="62" x2="${40 + i * 110}" y2="86" stroke="${C.teal}" stroke-width="2"/><text x="${72 + i * 110}" y="104" font-size="11" fill="${C.navy}">1 ft</text>`).join('')}<text x="120" y="48" font-size="14" font-weight="bold" fill="${C.teal}">3 × 12 = 36 inches</text>`),
    'Layers': fig('12 per layer × 3 layers = 36', `${[0,1,2].map(l => `<g transform="translate(${l * 18},${-l * 26})"><rect x="120" y="80" width="150" height="30" fill="${['#bfe6f2',C.sky,C.teal][l]}" stroke="${C.navy}"/><text x="278" y="100" font-size="11" fill="${C.navy}">layer ${l + 1}</text></g>`).join('')}<text x="90" y="140" font-size="13" font-weight="bold" fill="${C.navy}">12 cubes × 3 layers = 36</text>`),
    'Integers': fig('Integers on a number line', `<line x1="24" y1="80" x2="416" y2="80" stroke="${C.navy}" stroke-width="2"/><polygon points="418,80 408,75 408,85" fill="${C.navy}"/><polygon points="22,80 32,75 32,85" fill="${C.navy}"/>${Array.from({length:11}).map((_,i) => { const v = i - 5; const x = 40 + i * 36; return `<line x1="${x}" y1="73" x2="${x}" y2="87" stroke="${C.navy}"/><text x="${x}" y="104" font-size="10" text-anchor="middle" fill="${v === 0 ? C.coral : C.navy}" font-weight="${v === 0 ? 'bold' : 'normal'}">${v}</text>`; }).join('')}<circle cx="40" cy="80" r="5" fill="${C.coral}" stroke="${C.ink}"/><circle cx="364" cy="80" r="5" fill="${C.teal}" stroke="${C.ink}"/><text x="110" y="46" font-size="12" font-weight="bold" fill="${C.teal}">← smaller     0 in the middle     greater →</text>`),
    'Absolute value': fig('|−5| = 5 (distance from zero)', `<line x1="24" y1="90" x2="416" y2="90" stroke="${C.navy}" stroke-width="2"/><polygon points="418,90 408,85 408,95" fill="${C.navy}"/><polygon points="22,90 32,85 32,95" fill="${C.navy}"/>${Array.from({length:11}).map((_,i) => { const v = i - 5; const x = 40 + i * 36; return `<line x1="${x}" y1="84" x2="${x}" y2="96" stroke="${C.navy}"/><text x="${x}" y="112" font-size="10" text-anchor="middle" fill="${v === 0 ? C.coral : C.navy}" font-weight="${v === 0 ? 'bold' : 'normal'}">${v}</text>`; }).join('')}<circle cx="40" cy="90" r="6" fill="${C.coral}" stroke="${C.ink}"/><line x1="40" y1="66" x2="220" y2="66" stroke="${C.teal}" stroke-width="2.5"/><polygon points="38,66 48,61 48,71" fill="${C.teal}"/><text x="96" y="58" font-size="13" font-weight="bold" fill="${C.teal}">5 steps to zero</text>`),
    'Coordinate plane': fig('Coordinate grid: axes, origin, and four quadrants', `${[-4,-3,-2,-1,0,1,2,3,4].map(i => `<line x1="${220+i*30}" y1="30" x2="${220+i*30}" y2="210" stroke="#d7e6e0"/>`).join('')}${[-3,-2,-1,0,1,2,3].map(j => `<line x1="100" y1="${120-j*30}" x2="340" y2="${120-j*30}" stroke="#d7e6e0"/>`).join('')}<line x1="92" y1="120" x2="348" y2="120" stroke="${C.navy}" stroke-width="2"/><line x1="220" y1="22" x2="220" y2="218" stroke="${C.navy}" stroke-width="2"/><polygon points="350,120 340,115 340,125" fill="${C.navy}"/><polygon points="90,120 100,115 100,125" fill="${C.navy}"/><polygon points="220,20 215,30 225,30" fill="${C.navy}"/><polygon points="220,220 215,210 225,210" fill="${C.navy}"/><text x="354" y="124" font-size="11" font-weight="bold" fill="${C.navy}">x</text><text x="214" y="18" font-size="11" font-weight="bold" fill="${C.navy}">y</text>${[-4,-3,-2,-1,1,2,3,4].map(i => `<text x="${220+i*30}" y="134" font-size="8" fill="${C.navy}" text-anchor="middle">${i}</text>`).join('')}${[-3,-2,-1,1,2,3].map(j => `<text x="211" y="${120-j*30+3}" font-size="8" fill="${C.navy}" text-anchor="middle">${j}</text>`).join('')}<text x="207" y="133" font-size="8" fill="${C.navy}">O</text><text x="312" y="52" font-size="13" font-weight="bold" fill="${C.teal}">I</text><text x="300" y="66" font-size="9" fill="${C.ink}">(+, +)</text><text x="118" y="52" font-size="13" font-weight="bold" fill="${C.teal}">II</text><text x="104" y="66" font-size="9" fill="${C.ink}">(−, +)</text><text x="114" y="188" font-size="13" font-weight="bold" fill="${C.teal}">III</text><text x="104" y="174" font-size="9" fill="${C.ink}">(−, −)</text><text x="300" y="140" font-size="13" font-weight="bold" fill="${C.teal}">IV</text><text x="300" y="154" font-size="9" fill="${C.ink}">(+, −)</text><line x1="220" y1="120" x2="310" y2="120" stroke="${C.teal}" stroke-width="2.5" stroke-dasharray="4 3"/><line x1="310" y1="120" x2="310" y2="180" stroke="${C.gold}" stroke-width="2.5" stroke-dasharray="4 3"/><text x="244" y="114" font-size="9" font-weight="bold" fill="${C.teal}">right 3</text><text x="314" y="158" font-size="9" font-weight="bold" fill="${C.gold}">down 2</text><circle cx="310" cy="180" r="6" fill="${C.coral}" stroke="${C.ink}"/><text x="268" y="200" font-size="11" font-weight="bold" fill="${C.navy}">Point (3, −2) is in Quadrant IV</text>`, 224),
    'Fraction multiplication': fig('3/4 × 4 = 12/4 = 3', `${[0,1,2,3].map(g => `<rect x="${40 + g * 96}" y="56" width="80" height="30" fill="#fff" stroke="${C.navy}"/>${[0,1,2].map(i => `<rect x="${40 + g * 96 + i * 20}" y="56" width="20" height="30" fill="${C.gold}"/>`).join('')}<line x1="${40 + g * 96 + 60}" y1="56" x2="${40 + g * 96 + 60}" y2="86" stroke="${C.navy}"/>`).join('')}<text x="120" y="118" font-size="14" font-weight="bold" fill="${C.teal}">4 groups of 3/4 = 3 wholes</text>`),
    'Decimal operations': fig('2.4 ÷ 0.3 = 8', `<text x="70" y="82" font-size="26" font-family="Arial" font-weight="bold" fill="${C.navy}">2.4 ÷ 0.3</text><text x="270" y="82" font-size="26" font-family="Arial" font-weight="bold" fill="${C.teal}">= 8</text><text x="70" y="118" font-size="13" fill="${C.ink}">24 tenths ÷ 3 tenths = 8</text>`)
  };
}
const conceptVisualMap = conceptVisuals();
function visualForConcept(concept) { return conceptVisualMap[concept] || fig(concept, `<text x="60" y="86" font-size="16" font-weight="bold" fill="${C.navy}">${concept}</text>`); }
const conceptCases = {
  'Place value': [['Zero as a placeholder', 'In 305,072 the 0 in the thousands place holds the spot so the other digits keep their value, even though it adds nothing.'], ['Compare same-length numbers', 'For 45,210 and 45,120, start at the left and stop at the first place that differs. Here 2 hundreds beats 1 hundred.'], ['Say it in words', '642,908 is six hundred forty-two thousand, nine hundred eight.']],
  'Rounding': [['Round down', '386,499 to the nearest thousand is 386,000 because the hundreds digit 4 is less than 5.'], ['Round up', '386,749 to the nearest thousand is 387,000 because the hundreds digit is 7.'], ['The exact-5 rule', '386,500 rounds up to 387,000. A 5 in the checking place always rounds up.'], ['A 9 that carries', '386,950 to the nearest hundred becomes 387,000 because the extra hundred rolls into the thousands.']],
  'Add & subtract': [['Regroup once', '4,786 + 2,549: the ones make 15, so write 5 and carry 1 ten.'], ['Subtract across zeros', '5,003 − 1,478 has no tens or hundreds to borrow, so regroup from the thousands first.'], ['No regrouping', '5,321 + 2,146 needs no carrying because no column reaches ten.']],
  'Arrays': [['Turn it around', '3 × 4 and 4 × 3 both equal 12. Rotating the array keeps the total.'], ['A single row', '1 × 7 is just one row of 7.'], ['Build up', '5 rows of 6 is 5 × 6 = 30.']],
  'Area models': [['Two-digit by one-digit', '23 × 4 = (20×4) + (3×4) = 80 + 12 = 92.'], ['Two-digit by two-digit', '24 × 13 = (24×10) + (24×3) = 240 + 72 = 312.'], ['Add every part', 'Every rectangle counts; add all partial products.']],
  'Multi-digit products': [['Regroup as you go', '1,426 × 3: multiply each place and carry when a product passes nine.'], ['A zero inside', '1,206 × 4: the 0 tens still gets multiplied, giving 0 plus any carry.'], ['Estimate to check', '1,426 × 3 ≈ 1,400 × 3 = 4,200, so 4,278 is reasonable.']],
  'Equal groups': [['Shares evenly', '84 ÷ 6 = 14 with nothing left over.'], ['Leftover pieces', '85 ÷ 6 = 14 remainder 1.'], ['Check by multiplying', '6 × 14 = 84 proves the quotient.']],
  'Long division': [['Standard case', '864 ÷ 4 = 216, dividing hundreds, tens, then ones.'], ['Zero in the quotient', '816 ÷ 4 = 204, because 1 ten cannot be shared into 4 groups.'], ['Ends with a remainder', '865 ÷ 4 = 216 remainder 1.']],
  'Remainders': [['Round up', '29 students in vans of 6 need 5 vans, because the leftover 5 still ride.'], ['Drop it', '29 candies shared by 6 friends is 4 each; the extra 5 are set aside.'], ['Share as a fraction', '29 ÷ 6 can be written as 4 5/6 when the remainder is split.']],
  'Multi-step plans': [['Multiply then subtract', '6 boxes × 24 pencils = 144, then 144 − 17 = 127.'], ['Add then divide', '(12 + 18) ÷ 5 = 30 ÷ 5 = 6.'], ['Label each step', 'Write a small equation per step so you do not lose track.']],
  'Variables': [['Addition equation', 'n + 36 = 91 → n = 91 − 36 = 55.'], ['Subtraction equation', 'n − 12 = 30 → n = 30 + 12 = 42.'], ['Multiplication equation', '4n = 24 → n = 24 ÷ 4 = 6.']],
  'Factors': [['Composite', '24 has many factors, so it is composite.'], ['Prime', '23 has only 1 and 23, so it is prime.'], ['Special number 1', '1 has a single factor, so it is neither prime nor composite.']],
  'Unit conversions': [['Bigger to smaller', '4 feet × 12 = 48 inches; the number grows.'], ['Smaller to bigger', '48 inches ÷ 12 = 4 feet; the number shrinks.'], ['Write the fact first', 'Start with the relationship, like 1 foot = 12 inches.']],
  'Time and volume': [['Time', '3 minutes = 3 × 60 = 180 seconds.'], ['Mass', '3 kilograms = 3,000 grams.'], ['Capacity', '2 gallons = 8 quarts.']],
  'Area & perimeter': [['Find both', 'A 7 × 4 rectangle has area 28 and perimeter 22.'], ['Same perimeter, different area', 'A 6×2 and a 4×4 both have perimeter 16, but areas 12 and 16.'], ['Find a missing side', 'Area 28 with width 4 means length 28 ÷ 4 = 7.']],
  'Equivalent fractions': [['Build up', '1/2 = 2/4 = 4/8 by multiplying top and bottom.'], ['Simplify down', '6/8 = 3/4 by dividing top and bottom by 2.'], ['Compare fairly', '1/2 and 3/5 become 5/10 and 6/10, so 3/5 is greater.']],
  'Adding fractions': [['Like denominators', '3/8 + 2/8 = 5/8.'], ['Past one whole', '5/6 + 3/6 = 8/6 = 1 1/3.'], ['Keep the size', 'The denominator never changes when denominators already match.']],
  'Subtracting fractions': [['Like denominators', '7/10 − 3/10 = 4/10 = 2/5.'], ['From one whole', '1 − 3/8 = 8/8 − 3/8 = 5/8.'], ['Simplify', '4/10 shares a factor of 2, so it becomes 2/5.']],
  'Fraction groups': [['Whole-number result', '3 × 2/5 = 6/5 = 1 1/5.'], ['Stays a fraction', '2 × 1/6 = 2/6 = 1/3.'], ['Model the groups', 'Draw the fraction that many times, then combine.']],
  'Tenths & hundredths': [['Tenths', '0.7 means 7/10.'], ['Hundredths', '0.35 means 35/100.'], ['Equal decimals', '0.3 and 0.30 name the same amount.']],
  'Compare decimals': [['Same length', '0.75 > 0.70 because 75 hundredths beats 70.'], ['Different lengths', '0.6 vs 0.06: line up as 0.60 and 0.06, so 0.60 is greater.'], ['Equal values', '0.5 = 0.50 after adding a placeholder zero.']],
  'Lines': [['Name the figure', 'A line has two arrows, a segment two endpoints, a ray one endpoint.'], ['Parallel', 'Two lines that never meet, like train tracks.'], ['Perpendicular', 'Two lines that cross at a square 90° corner.']],
  'Angles': [['Acute', 'Smaller than a square corner, like 45°.'], ['Right', 'Exactly a square corner, 90°.'], ['Obtuse and straight', 'Obtuse is between 90° and 180°; a straight angle is exactly 180°.']],
  'Symmetry': [['No lines', 'A scalene triangle has 0 lines of symmetry.'], ['One line', 'An isosceles triangle has exactly 1 line of symmetry.'], ['Many lines', 'A square has 4 lines of symmetry.']],
  'Expressions': [['Parentheses first', '(8 + 2) × 5 = 10 × 5 = 50.'], ['No parentheses', '8 + 2 × 5 = 8 + 10 = 18, because you multiply before adding.'], ['Work inside out', 'Solve the innermost group first.']],
  'Perimeter': [['Add all sides', 'A 6 by 4 rectangle: 6+4+6+4 = 20.'], ['Square shortcut', 'A square with side 5 is 4 × 5 = 20.'], ['Irregular shape', 'Add every side length, even the short ones.']],
  'Area': [['Rectangle', '6 × 4 = 24 square units.'], ['Square', 'Side 5 gives 5 × 5 = 25 square units.'], ['Missing side', 'Area 24 with length 6 means width 24 ÷ 6 = 4.']],
  'Whole numbers': [['Add in columns', '47,891 + 23,109 = 71,000.'], ['Subtract across zeros', '40,000 − 12,345 borrows through the zeros.'], ['Estimate first', 'Round to check that the answer is sensible.']],
  'Decimals': [['Add', '3.40 + 0.65 = 4.05.'], ['Subtract', '5.20 − 1.75 = 3.45.'], ['Different lengths', 'Line up points and add zeros: 3.4 becomes 3.40.']],
  'Straight lines': [['Find the partner', 'If one angle is 70°, the other is 110°.'], ['Check the total', 'The two angles must add to exactly 180°.'], ['Right-angle split', 'Two 90° angles also make a straight line.']],
  'Polygons': [['Name by sides', '3 sides is a triangle, 4 a quadrilateral, 5 a pentagon, 6 a hexagon.'], ['Regular vs irregular', 'A regular hexagon has equal sides; an irregular one does not.'], ['Not a polygon', 'A shape with a curve or a gap is not a polygon.']],
  'Addition': [['Common denominator', '1/3 + 1/6 = 2/6 + 1/6 = 1/2.'], ['Sum to one', '1/4 + 3/4 = 4/4 = 1.'], ['Rename first', 'Change unlike denominators before adding.']],
  'Subtraction': [['Common denominator', '3/4 − 1/4 = 2/4 = 1/2.'], ['Unlike denominators', '5/6 − 1/3 = 5/6 − 2/6 = 1/2.'], ['Simplify', 'Reduce the final fraction when possible.']],
  'Volume': [['Multiply three', '4 × 3 × 2 = 24 cubic units.'], ['Count cubes', 'A layer of 12 with 2 layers is 24.'], ['Missing dimension', 'Volume 24 with a base of 12 means height 24 ÷ 12 = 2.']],
  'Conversions': [['Length', '3 feet = 36 inches.'], ['Capacity', '2 liters = 2,000 milliliters.'], ['Direction', 'Bigger to smaller multiplies; smaller to bigger divides.']],
  'Layers': [['Equal layers', '12 cubes per layer × 3 = 36 cubic units.'], ['More layers', '12 × 5 = 60 cubic units.'], ['Find layers', '36 cubes with 12 per layer means 3 layers.']],
  'Integers': [['Order', '−3 is left of 0 and less than 4.'], ['Compare negatives', '−2 > −5 because it is closer to zero.'], ['Zero', 'Zero is neither positive nor negative.']],
  'Absolute value': [['Negative input', '|−5| = 5.'], ['Positive input', '|5| = 5.'], ['Zero', '|0| = 0, since it sits on zero.']],
  'Coordinate plane': [['Quadrant I', '(3, 2) is right and up.'], ['Quadrant IV', '(3, −2) is right and down.'], ['On an axis', '(0, 4) sits on the y-axis; (−5, 0) sits on the x-axis.']],
  'Fraction multiplication': [['Whole result', '3/4 × 4 = 12/4 = 3.'], ['Mixed result', '2/3 × 5 = 10/3 = 3 1/3.'], ['Simplify', 'Reduce or convert to a mixed number at the end.']],
  'Decimal operations': [['Divide', '2.4 ÷ 0.3 = 8.'], ['Multiply', '2.4 × 3.5 = 8.40.'], ['Estimate', 'Estimate first so the decimal point lands correctly.']]
};
function casesForConcept(concept) { const cases = conceptCases[concept]; return cases ? `<div class="concept-cases"><p class="cases-heading">Explore every case</p><div class="case-grid">${cases.map(([title, text]) => `<div class="case-card"><b>${title}</b><span>${text}</span></div>`).join('')}</div></div>` : ''; }
function startChapter(index) { state.chapter = index; state.concept = null; state.question = 0; state.attempts = 0; const key = `${state.subject}-${state.grade}-${index}`; if (!state.started.includes(key)) { state.started.push(key); save(); } $('#emptyState').hidden = true; $('#lessonView').hidden = false; renderConceptPicker(); renderChapters(); $('#playground').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderConceptPicker() { const chapter = currentChapter(); $('#lessonView').innerHTML = `<section class="lesson-panel concept-picker"><p class="chapter-label">Chapter ${state.chapter + 1}</p><h2>${chapter[0]}</h2><p class="lesson-copy">Pick one skill. Every skill mission has 10 questions and earns its own trophy.</p><div class="concept-choice-grid">${chapter[1].map((concept,index) => `<button class="concept-choice" data-start-concept="${index}"><span>${index + 1}</span><strong>${concept}</strong><small>10-question mission</small></button>`).join('')}</div></section>`; document.querySelectorAll('[data-start-concept]').forEach(button => button.addEventListener('click', () => { state.concept=Number(button.dataset.startConcept); state.question=0; state.attempts=0; state.answers={}; renderLesson(); })); }
function placeValueVisual() { return `<div class="place-chart"><div class="chart-number">582,641</div><div class="chart-row"><b>Hundred-thousands</b><b>Ten-thousands</b><b>Thousands</b><b>Hundreds</b><b>Tens</b><b>Ones</b></div><div class="chart-row chart-values"><span>5<br><small>500,000</small></span><span class="focus">8<br><small>80,000</small></span><span>2<br><small>2,000</small></span><span>6<br><small>600</small></span><span>4<br><small>40</small></span><span>1<br><small>1</small></span></div></div>`; }
function renderLesson() {
  const chapter = currentChapter(), question = currentQuestion(), concept = chapter[1][state.concept], complete = state.answers[state.question];
  const lesson = state.grade === 4 && state.chapter === 0 && state.concept === 0 ? '<p class="lesson-copy"><strong>Place value tells us what a digit is worth because of where it sits.</strong> The digit 8 in 582,641 is not worth eight. It is in the ten-thousands place, so it is worth 80,000. Each step left is 10 times greater; each step right is 10 times smaller.</p>' + placeValueVisual() + '<p class="lesson-copy"><strong>Read it in chunks:</strong> 582,641 is five hundred eighty-two thousand, six hundred forty-one. Use the chart to name a digit, write a number, compare numbers, or build expanded form.</p>' + casesForConcept('Place value') : `${lessonForConcept(concept, chapter[2])}${visualForConcept(concept)}${casesForConcept(concept)}`;
  $('#lessonView').innerHTML = `<div class="lesson-layout"><section class="lesson-panel"><p class="chapter-label">Chapter ${state.chapter + 1} · Concept mission</p><div class="concept-mission-nav"><button class="text-button" id="backToConcepts">← All concepts</button><span>${state.concept + 1} of ${chapter[1].length}</span></div><h2>${concept}</h2>${lesson}<p class="lesson-copy"><strong>Mission tip:</strong> Use the model, then explain to yourself why the answer makes sense.</p><div class="concept-arrows"><button class="primary-button muted-button" id="previousConcept" ${state.concept===0?'disabled':''}>← Previous concept</button><button class="primary-button" id="nextConcept" ${state.concept===chapter[1].length-1?'disabled':''}>Next concept →</button></div></section><section class="question-panel"><div class="question-meta"><span>Question ${state.question + 1} of 10</span><span class="attempt-dots">${[0, 1, 2].map(index => `<i class="${index < state.attempts ? 'used' : ''}"></i>`).join('')}</span></div><div class="question-nav">${currentQuestions().map((_,index) => `<button data-go="${index}" class="nav-dot ${index===state.question?'active':''} ${state.answers[index]?'done':''}" title="Question ${index + 1}">${index + 1}</button>`).join('')}</div><h2>${question.question}</h2><div class="answer-list">${question.options.sort(() => Math.random() - .5).map(answer => `<button class="answer-button" data-answer="${answer}" ${complete?'disabled':''}>${answer}</button>`).join('')}</div><p class="feedback" id="feedback">${complete ? 'Completed! Nice persistence. Use the arrows or number buttons to visit another question.' : 'Choose the answer that makes the math story true.'}</p><div class="question-arrows"><button class="icon-button" id="previousQuestion" ${state.question===0?'disabled':''} title="Previous question">←</button><button class="icon-button" id="nextQuestion" ${state.question===9?'disabled':''} title="Next question">→</button></div></section></div>`;
  document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => { state.question=Number(button.dataset.go); state.attempts=0; renderLesson(); }));
  $('#previousQuestion').addEventListener('click', () => { state.question--; state.attempts=0; renderLesson(); }); $('#nextQuestion').addEventListener('click', () => { state.question++; state.attempts=0; renderLesson(); });
  $('#backToConcepts').addEventListener('click', renderConceptPicker);
  $('#previousConcept').addEventListener('click', () => { state.concept--; state.question=0; state.attempts=0; state.answers={}; renderLesson(); });
  $('#nextConcept').addEventListener('click', () => { state.concept++; state.question=0; state.attempts=0; state.answers={}; renderLesson(); });
  document.querySelectorAll('[data-answer]').forEach(button => button.addEventListener('click', () => checkAnswer(button, question)));
}
const celebrations = ['🎉 Correct! You nailed it!', '🏆 Champion move! Keep going!', '⭐ Star work! That was sharp!', '🌟 Brilliant! Your brain is glowing!', '✨ Magical math! Well done!', '🚀 Blast off! Straight to the answer!', '💪 Strong thinking! You have got this!', '🔥 On fire! That was hot!', '👏 Bravo! Perfectly solved!', '🥳 Woohoo! You did it!', '🎯 Bullseye! Right on target!', '🧠 Big brain energy! Nice!', '💡 Bright idea! Spot on!', '👍 Thumbs up! Great choice!', '😎 Cool and correct!', '🙌 High five! Amazing!', '🏅 Gold-medal math!', '💯 One hundred percent right!', '⚡ Lightning fast and correct!', '🌈 Beautiful work!', '🦄 Magically correct!', '🎊 Party time! You got it!', '🍀 Lucky and smart!', '👑 Math royalty! Superb!', '💎 A diamond answer!', '🚩 Flag it — that is a win!', '🎉 Yes! Exactly right!', '🏆 Winner! Keep climbing!', '⭐ Shining bright! Correct!', '🌟 Superstar solving!', '✨ Sparkling smart!', '🚀 You are rocketing ahead!', '💪 Powerful thinking!', '🔥 Red hot and right!', '👏 Clap clap! Well earned!', '🥳 Celebrate — you are correct!', '🎯 Dead center! Nice aim!', '🧠 Smart cookie! Correct!', '💡 Lightbulb moment! Yes!', '👍 Nailed it! Great job!', '😎 Smooth solving!', '🙌 Fantastic! Keep it up!', '🏅 Medal-worthy answer!', '💯 Perfect! Totally right!', '⚡ Zap! Correct in a flash!', '🌈 Colorful thinking! Yes!', '🦄 One-of-a-kind smart!', '🎊 Confetti for you!', '🍀 Clever clover! Correct!', '👑 You rule this math!', '💎 Precious and precise!', '🎉 Hooray! You solved it!', '🏆 Top of the class!', '⭐ You earned a star!', '🌟 Glowing with genius!', '✨ Pure math magic!', '🚀 Sky-high skills!', '💪 Muscle up — correct!', '🔥 Blazing brilliant!', '👏 Give yourself a hand!', '🥳 Big win! Yes!', '🎯 Right on the mark!', '🧠 Genius alert! Correct!', '💡 So bright! Well done!', '👍 Great pick! Correct!', '😎 You made it look easy!', '🙌 Way to go!', '🏅 A winner answer!', '💯 Flawless! Correct!', '⚡ Super quick and right!', '🌈 Over the rainbow!', '🦄 Unbelievably good!', '🎊 Time to celebrate!', '🍀 Fortune favors the smart!', '👑 Crowned correct!', '💎 Shiny and correct!', '🎉 That is the one! Yes!', '🏆 Trophy-level thinking!', '⭐ You are a star solver!', '🌟 Dazzling! Correct!', '✨ Twinkling talent!', '🚀 Full speed to success!', '💪 Mighty math move!', '🔥 You are heating up!', '👏 Standing ovation!', '🥳 Party for your brain!', '🎯 Perfect aim again!', '🧠 Brainpower unlocked!', '💡 Genius spark! Correct!', '👍 Right again! Awesome!', '😎 Effortlessly correct!', '🙌 You are unstoppable!', '🏅 Champion answer!', '💯 Spot-on! Correct!', '⚡ Electric! Right answer!', '🌈 Bright and correct!', '🦄 Rare brilliance!', '🎊 Cheers to you!', '🍀 Smartly done!', '🌟 Amazing! On to the next!'];
function celebrate() { return celebrations[Math.floor(Math.random() * celebrations.length)]; }
function checkAnswer(button, question) {
  const right = question.correct;
  if (button.dataset.answer === right) {
    button.classList.add('correct'); document.querySelectorAll('[data-answer]').forEach(answer => answer.disabled = true); state.sparks += 1; state.answers[state.question]=true; save(); $('#sparkCount').textContent = `${state.sparks} sparks`; $('#feedback').innerHTML = `<span class="cheer">${celebrate()}</span>`; if (Object.keys(state.answers).length === 10) setTimeout(showResults, 700); return;
  }
  button.classList.add('wrong'); state.attempts += 1;
  if (state.attempts < 3) { const concept = currentChapter()[1][state.concept]; $('#reteachModal').hidden = false; $('#reteachContent').innerHTML = `${lessonForConcept(concept, currentChapter()[2])}${visualForConcept(concept)}<p class="lesson-copy"><strong>Try a fresh approach:</strong> Look at the picture, then match the numbers in the question to the model.</p>`; }
  else { document.querySelectorAll('[data-answer]').forEach(answer => answer.disabled = true); $('#feedback').innerHTML = `<strong>The answer is ${right}.</strong><div class="solution-box">${explain(question)}</div><button class="primary-button" id="continueButton">Continue to the next challenge</button>`; $('#continueButton').addEventListener('click', nextQuestion); }
}
function explain(question) { return `Use the concept model step by step. The answer that fits the question is <strong>${question.correct}</strong>.`; }
function showResults() { const misses = Math.max(0, 10 - state.sparks % 10); const tier = misses <= 1 ? ['Diamond','◆','Outstanding precision. You are ready for a tougher mission.'] : misses <= 4 ? ['Gold','★','Excellent work. Your practice is paying off.'] : misses <= 7 ? ['Silver','●','Strong persistence. Keep building this skill.'] : ['Bronze','▲','You stayed with it. Practice turns effort into power.']; state.trophies.push({ tier:tier[0], symbol:tier[1], concept:currentChapter()[1][state.concept] }); save(); $('#lessonView').innerHTML=`<section class="lesson-panel success-card"><div class="trophy ${tier[0].toLowerCase()}">${tier[1]}</div><p class="eyebrow">Mission complete</p><h2>${tier[0]} trophy earned</h2><p class="lesson-copy">${tier[2]}</p><p class="lesson-copy">You completed all 10 <strong>${currentChapter()[1][state.concept]}</strong> questions. Visit your trophy cabinet to see your growing collection.</p><button class="primary-button" id="backToConcepts">Choose another concept</button></section>`; $('#backToConcepts').addEventListener('click',renderConceptPicker); }
function renderRewards() { const counts = ['Diamond','Gold','Silver','Bronze'].map(tier => [tier, state.trophies.filter(item => item.tier === tier).length]); $('#rewardsContent').innerHTML = `<div class="reward-totals">${counts.map(([tier,count]) => `<div class="reward-total ${tier.toLowerCase()}"><b>${tier}</b><strong>${count}</strong></div>`).join('')}</div>${state.trophies.length ? `<div class="trophy-list">${state.trophies.slice().reverse().map(item => `<div class="trophy-item ${item.tier.toLowerCase()}"><span>${item.symbol}</span><div><b>${item.tier} trophy</b><small>${item.concept}</small></div></div>`).join('')}</div>` : '<p class="lesson-copy">Your cabinet is waiting. Complete a 10-question concept mission to earn your first trophy.</p>'}`; }
$('#tryAgain').addEventListener('click', () => { $('#reteachModal').hidden = true; renderLesson(); });
$('#openRewards').addEventListener('click', () => { renderRewards(); $('#rewardsModal').hidden = false; });
$('#closeRewards').addEventListener('click', () => { $('#rewardsModal').hidden = true; });
$('#resetProgress').addEventListener('click', () => { state.sparks = 0; state.started = []; state.trophies = []; save(); $('#sparkCount').textContent = '0 sparks'; renderChapters(); });
$('#sparkCount').textContent = `${state.sparks} sparks`; renderSubjectTabs(); renderGradeRail(); renderChapters();